lst=[10,20,30,40]
print("original list:",lst)
print("lenght:",len(lst))
print("count of 20:",lst.count(20))
print("index of 30:",lst.index(30))
lst.append(50)
print("after append(50):",lst)
lst.insert(2,25)
print("after a index at index 2 :",lst)
lst.extend([60,70])
print("after extend:",lst)
lst.remove(25)
print("after remove 25:",lst)
lst.pop()
print("after pop():",lst)
lst.reverse()
print("after reverse():",lst)
lst.sort()
print("after sort():",lst)
copy_list=lst.copy()
print("copied list:",copy_list)
lst.clear()
print("after clean():",lst)
