t=(5,3,8,6,3)
print("tuple:",t)
print("lenght:",len(t))
print("count of 3:",t.count(3))
print("index of 8:",t.index(8))
print("sorted:",sorted(t))
print("min:",min(t))
print("max:",max(t))
t2=(5,3,8)
print("comprsion with(5,3,8):",t==t2)
print("reversed:",tuple(reversed(t)))