s={10,20,30}
print("original set:",s)
s.add(40)
print("after add(40):",s)
s.update([50,60])
print("after update([50,60]):",s)
s2=s.copy()
print("copied set:",s2)
s.pop()
print("after pop():",s)
s.discard(20)
print("after discard(20):",s)
s.remove(30)
print("after remove(30):",s)
s.clear()
print("after clean():",s)