d={'name':'bob','age':22,'city':'rajkot'}
print("original dictionary:",d)
print("lenght:",len(d))
print("get'age':",d.get('age'))
d.update({'gender':'male'})
print("after update:",d)
d.pop('city')
print("after pop('city'):",d)  
print("keys:",d.keys())
print("values:",d.values())
print("items:",d.items())
d2=d.copy()
print("copied dictionary:",d2)
d.clear()
print("after clean:",d)     